server:
  port: 8080

spring:
  application:
    name: JAVA course - summer 26
  profiles:
    active: domaci1

  datasource:
    url: jdbc:mysql://localhost:3306/biblioteka_summer
    username: root
    password: nikola2003
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true